task:  # multi-classification, binary-classification, regression
model: # model to use
model_arguments: # hyperparameters to tune the model
target_column :  # name of the column of the dataset which corresponds to the target

dataset_split_proportions: # percentage of the dataset that goes into train, validation and test
  train:
  validation:  # set to 0 to not use a validation set, e.g. if you have a small amount of data, you may prefer cross-validation.
  test:

cross_validation:
  run:  # Whether to cross-validate the test set. Usually used if no validation set is provided
  folds_number: # Number of cross-validation folds

hyperoptimization: # Hyperoptimization will be run if an optimization dict functions is passed to run_training_pipeline
  evaluations_number: # Number of iterations of the hyperoptimization
  metric:  # which metric to use for the evaluation criteria. Check the section on metrics to see the metrics available.
  metric_decreases_when_optimized: # Whether the above metric decreases when it is optimized